### PR TITLE
Turkish

### PR DESCRIPTION
**Pull request by alerque**
Turkish support is working reasonably well for me and I've gone back and cleaned up the code and commits a bunch so they are presentable now. I'd like to see this added upstream at some point. However there are still a couple unresolved issues. I'm happy to do the work to fix them, but I'm rather at a loss as to what end of the snake to grab onto.
1. Turkish works fine by itself, but it won't compile into the "full" edition because of a conflict with Hungarian. Specifically the book of Judges has an abbreviation of Bír which, because matches are made without accents, includes "Bir" … the Turkish number "One". As I have that listed as one possible way of denoting the "First Xxxxx" books that creates a conflict. I'm not sure why it doesn't go for longest match first and just roll with it, but for whatever reason that is a blocker in the full compile.
2. A couple "Recurse" notices pop up during compile for the Gospels. I can't quite make out what causes these.

### CODE REVIEW

**Comment by alerque** [comment]
Geez, I've been running this for two months on a staging site and nobody caught that I spelled Thessalonians wrong and it wasn't matching...until half an hour after I finally post this PR. Standby...

**Comment by alerque** [comment]
There, that's better.

I would like to add support for a bunch more abbreviated matches (e.g. three letter book name abbreviations with a number as in "1 Sel"; currently only the standardized three letter "1 Se" works), but I think it might be good to hold off on them until I get a better handle on which ones make sense to use. I don't have a good corpus to go off of and people don't seem to publish with them, but they sure do search for them when typing in lookups. At some point I'll sort through my logs and pick out the ones that make sense and aren't just typos or other noise. But that point isn't now.

**Comment by openbibleinfo** [comment]
What do you think of putting the various "i" characters into brackets rather than parentheses? I've updated 01.add_lang.pl to make that feasible. I also wasn't sure whether in data.txt the $TRANS should be YC198 rather than YC1998 and whether the $VERSE should be "a.[space]ayeti" as opposed to "a.[\t]ayeti".

By default, 01.add_lang.pl treats "." as an optional character, so it's not necessary to put a "?" after it.

**Comment by openbibleinfo** [comment]
Apparently I created a new pull request instead of updating this one. Sorry. https://github.com/openbibleinfo/Bible-Passage-Reference-Parser/pull/18

**Comment by alerque** [comment]
@openbibleinfo I like the bracket syntax a lot better. I must have tried two dozen ways to make it work before resorting to the parenthesis syntax, but I was trying to work inside the data file without editing the parser. If the upstream code really accounts for the problem now that will be great.

I did spot a couple things just glancing over the changes that might be an issue. I'll do some testing early next week and see how it goes. Sorry I don't have time to play with it today.

As for the PR situation, that's fine. You couldn't actually add commits directly to this PR as it is against a branch in my fork. You could have pushed the branch and just linked the commit without opening the PR, but that's fine too. Either way I can get my hands on it and add it to my branch for testing, so it's all good.

**Comment by alerque** [comment]
@openbibleinfo There are a couple of ways that your refactored verse is definitely better. I'm working on integrating it into a site now and we'll see how things go. One concern I did have that might be a step backwards is that you're generating quite a lot of potential book name matches that are quite unlikely to actually occur in the wild (to be fair my version had quite a few too, but now there are ever more). It's quite common form Turkish characters to be typed on English keyboard with their nearest equivalent characters, but it's fairly unusual for letters in the English alphabet to get typed with similar but different Turkish characters. For example one might type Romalılar as Romalilar if you were on a keyboard without a Turkish undotted-i, but it would be very weird and an abuse of spelling to write Selanikliler as Selanıklıler. It's just wrong and I'm not sure there is any point in matching it. Mind you this is only for the lower case, you _do_ have to catch the upper case variants SELANİKLİLER (correct) and SELANIKLILER (wrong, but the way it would be typed on an English keyboard). For most words this is unlikely to cause false positives, but it does seem like a lot of overhead.

The second part of that is that there isn't a lot of point in mixing and matching. The only cases I care about are the ones that are all one way or another. Again this seems like a lot of overhead for a dubious advantage in matching.

Thoughts?

**Comment by openbibleinfo** [comment]
Yes, I agree that the current approach is leading to a combinatorial explosion--there are over 9,000 abbreviations here, mostly because of the "i" variants. If you want to force only consistent "i" variants, as you describe, I _think_ the best way would be to include them individually, fully specified, rather than use brackets. So you'd have:

> $FIRST Selanikliler    (tab)   $FIRST SELANİKLİLER

The first one handles both the uppercase "I" and the lowercase "i", and the second handles the all-caps variant. This approach generates only two possibilities instead of six.

The only other caveat is that some people do appear to use "1 Selanıklıler": https://www.google.com/search?q=%221%20Selan%C4%B1kl%C4%B1ler%22&ie=utf-8&oe=utf-8 . Whether that means you want to include this third variant is up to you.

**Comment by alerque** [comment]
Bah humbug. And now there are going to be 5 Google hits instead of 4 because it's going to pick up this thread. The faster we can make that bogus rendition die the better if you ask me. I'd rather my app not match it at all. I don't at all mind catching potential typing errors, copy paste and casing issue, keyboard issue, etc. but I'd just assume not encourage outright bogus miss-spellings as valid usage.

**Comment by alerque** [comment]
Rebased commits to account for some corrections based on feedback to date. Still matching a lot of i's, but now with other issues corrected.

**Comment by openbibleinfo** [comment]
I'm finishing up the November release. Do you have a data.txt that you feel is ready to merge into master, or would you rather wait?

**Comment by alerque** [comment]
Turkish support is plenty mature to include any time. I've had it in production in several places for a long time now and tweaked it for a lot of little things that come up. The catch right now is because your workflow seems to eschew normal Github style contributing, I'm currently maintaining this in my master branch so I can use it as an NPM module directly.

If you let me know when you're ready to merge this I'll rebase it and put it here.

**Comment by openbibleinfo** [comment]
Added to 2.0.1.

**Pull request closed without merging**
